server.port: 8081

mailgun.key: b727c4a130956463d68f74d02e8d45d0-381f2624-07871405
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
feign:
  okhttp.enabled: true
  autoconfiguration:
    jackson:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zero_order?useSSL=false&useUnicode-true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zerobase

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
