server:
  port: 8082
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zero_order?useSSL=false&useUnicode-true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zerobase

  mvc.pathmatch.matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop

  redis:
    host: localhost
    port: 6379

feign:
  client:
    url:
      user-api: localhost:8081